branches:
  only:
    - automate
language: python
python:
  - "2.7"
before_install:
  - git submodule init && git submodule update
  - (cd meetup2md; git submodule init && git submodule update)
install:
  - pip install --requirement requirements.txt
  - (cd meetup2md; pip install --requirement requirements.txt)
