branches:
  only:
  - automate
language: python
python:
- 2.7.11
before_install:
- openssl aes-256-cbc -K $encrypted_49256425b317_key -iv $encrypted_49256425b317_iv
  -in .meetup2md.cfg.enc -out /tmp/.meetup2md.cfg -d
- git submodule init && git submodule update
- "(cd meetup2md; git submodule init && git submodule update)"
install:
- pip install --requirement requirements.txt
- "(cd meetup2md; pip install --requirement requirements.txt)"
script:
  - |
     ./meetup2md/meetup2md.py --config /tmp/.meetup2md.cfg --output-dir content/posts --status upcoming --time-range ,1m --group-name SGVTech --name-filter 'SGV Linux Users Group Monthly Meeting' --cleanup '^SGV Linux Users Group Monthly Meeting -' 2>/tmp/meetup2md.2 | grep 'content/posts' | sed 's/ -> //g' > /tmp/meetup.posts
  - |
     [ "$(grep -ie error /tmp/meetup2md.2)" ] && { cat /tmp/meetup2md.2; exit 1; }
  - |
     [ "$(grep -E ? /tmp/meetup.posts)" ] && cat /tmp/meetup2md.posts || { echo "No new Meetup posts found"; exit 1; }
  - make publish
